# Numpy Assignment

##### 1. Create a 1D array of numbers from 0 to 9.

In [1]:
import numpy as np

In [6]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


##### 2. Create a 3×3 numpy array of all True’s

In [11]:
boolArr = np.ones((3,3),dtype=bool) * True
print(boolArr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


##### 3. Given an array as input, print only odd numbers as output

In [14]:
arr = np.arange(0,50)
print(arr[arr.flatten() % 2 == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


##### 4. Replace all odd numbers in arr with -2

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
mod_arr = np.where(arr%2 == 0,arr , -2)
print(mod_arr)

[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


##### 5. How to reshape an array?

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mod_arr = arr.reshape(6,2)
print(mod_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


##### 6. Convert a 1D array to a 2D array with 2 rows

In [43]:
arr = np.arange(0,20)
if arr.shape[0]%2 == 0:
    d = int(arr.shape[0]/2)
    mod_arr = arr.reshape(d,2)
    print(mod_arr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


##### 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [83]:
a = [1,2,3,4,5,6,7,8,9]
arr = np.array(a)
mod_arr = arr[not(np.where(arr%2 == 1)) or np.where(arr%4 == 0)]
print(mod_arr)


[4 8]


##### 8. Given array, check if there are any null values and print them out. 


##### 9. How to replace all missing values with 0 in a numpy array?

##### Not Applicable

##### 10. How to find the count of each unique number in a NumPy array?



In [88]:
np.random.seed(29)
rArray = np.random.randint(4,size=(5,5))

uniqueMap ={}
for item in rArray.flatten():
    if (item in uniqueMap.keys()):
        uniqueMap[item] = uniqueMap[item] + 1
    else:
        uniqueMap[item] = 1
        
    
print(uniqueMap)

{1: 8, 3: 5, 0: 8, 2: 4}


##### 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

In [89]:
rArray = np.random.randint(500,size=(10,10))

reqList = []
for obj in rArray.flatten():
    if((obj % 5 == 0) or (obj %7 == 0)):
        reqList.append(obj)
    
print(reqList)
    

[130, 15, 430, 150, 205, 252, 250, 20, 220, 390, 84, 285, 448, 315, 115, 170, 475, 462, 469, 154, 465, 220, 270, 310, 55, 406]


##### 13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [93]:
arr = np.arange(0,20)

modArr = arr[-1:0:-1]
print(modArr)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
